name: Windows Dotnet Workflow

on:
  workflow_call:
  

jobs:
  build-go-project:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./dotnet-projects
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run command
        run: |
          Write-Output "runner-dotnet project"