name: GoLang Releaser Workflow

on:
  workflow_call:
  

jobs:
  build-go-project:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go-projects
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Build go
        run: |
          go build