name: Bootstrap Starter Workflow
on:
  workflow_call:
    inputs: 
      buildtype: 
        description: 'Platform to build'
        required: true
        type: string  
      release_dir: 
        description: 'release_dir property from integration-manifest.json'
        required: true
        type: string  
      update_catalog: 
        description: 'update_catalog property from integration-manifest.json'
        required: true
        type: string  

jobs:
  call-create-github-release-workflow:
    uses: Keyfactor/actions/.github/workflows/github-release.yml@support-hotfixes

  call-dotnet-build-and-release-workflow:
    needs: [call-create-github-release-workflow]
    if: inputs.buildtype == 'dotnet'
    uses: fiddlermikey/actions/.github/workflows/dotnet-build-and-release.yml@main
    with:
      release_version: ${{ needs.call-create-github-release-workflow.outputs.release_version }}
      release_url: ${{ needs.call-create-github-release-workflow.outputs.release_url }}
      release_dir: ${{ inputs.release_dir }}

    secrets: 
      token: ${{ secrets.PRIVATE_PACKAGE_ACCESS }}

  call-go-build-and-tag-workflow:
    needs: [call-create-github-release-workflow]
    if: inputs.buildtype == 'golang'
    uses: fiddlermikey/actions/.github/workflows/go-build-and-tag.yml@main
    with:
      release_version: ${{ needs.call-create-github-release-workflow.outputs.release_version }}


    secrets: 
      token: ${{ secrets.PRIVATE_PACKAGE_ACCESS }}

  #call-generate-readme-workflow:
  #  if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
  #  uses: Keyfactor/actions/.github/workflows/generate-readme.yml@main
  #  secrets:
  #    token: ${{ secrets.APPROVE_README_PUSH }}

  #call-update-catalog-workflow:
  #  if: inputs.update_catalog == 'True' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
  #  uses: Keyfactor/actions/.github/workflows/update-catalog.yml@main
  #  secrets: 
  #    token: ${{ secrets.SDK_SYNC_PAT }}
